spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/root?serverTimezone=Asia/Seoul
    username: root
    password: justine1182

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

llm:
  api:
    key: "temporary_api_key_for_local_test"

jwt:
  token: "your_temporary_secret_key_for_local_development_at_least_32_chars"
